"""The committed spec pipeline artifacts, generated by `tools_dev/prune_spec.py`.

The four data files are generated from the pinned Stripe OpenAPI snapshot — do
not edit them by hand; regenerate with `python -m tools_dev.prune_spec` (the
source spec is git-ignored; see `research/MANIFEST.md`). This `__init__` is the
one hand-written module among them: it re-exports the closed sets the schema's
CHECK constraints, `emit_event` and the conformance validator read
(components/discovery.md), and loads `spec3.min.json` once per process for the
discovery index, the serializer and the expansion resolver. The subset of
Stripe's spec in this directory is MIT-licensed material — see
`THIRD_PARTY_LICENSES.md`.
"""

import json
from functools import cache
from importlib import resources
from typing import Any

from stripeapi.spec.enums import DOC_ONLY_ENUMS
from stripeapi.spec.event_types import EVENT_TYPES
from stripeapi.spec.expandable import EXPANDABLE_FIELDS

__all__ = [
    "DOC_ONLY_ENUMS",
    "EVENT_TYPES",
    "EXPANDABLE_FIELDS",
    "spec_document",
]


@cache
def spec_document() -> dict[str, Any]:
    """The pruned spec, parsed once per process.

    ~1.3 MB and ~11 ms to parse (`components/discovery.md` §3), shared by
    reference across every instance a process serves: discovery's index, the
    serializer's presence sets and the expansion resolver all read this one
    copy rather than each opening the file.
    """
    text = resources.files("stripeapi.spec").joinpath("spec3.min.json").read_text()
    return json.loads(text)  # type: ignore[no-any-return]
