"""The committed spec pipeline artifacts, generated by `tools_dev/prune_spec.py`.

Everything here is generated from the pinned Stripe OpenAPI snapshot — do not
edit by hand; regenerate with `python -m tools_dev.prune_spec` (the source spec
is git-ignored; see `research/MANIFEST.md`). `spec3.min.json` is package data
loaded by the discovery layer; the three Python constants are the closed sets
the schema's CHECK constraints, `emit_event` and the conformance validator read
(components/discovery.md). The subset of Stripe's spec in this directory is
MIT-licensed material — see `THIRD_PARTY_LICENSES.md`.
"""

from stripeapi.spec.enums import DOC_ONLY_ENUMS
from stripeapi.spec.event_types import EVENT_TYPES
from stripeapi.spec.expandable import EXPANDABLE_FIELDS

__all__ = ["DOC_ONLY_ENUMS", "EVENT_TYPES", "EXPANDABLE_FIELDS"]
