"""Generated by tools_dev/prune_spec.py from Stripe's OpenAPI spec — do not edit.

Regenerate with `python -m tools_dev.prune_spec`. The source spec carries the
MIT licence; see THIRD_PARTY_LICENSES.md.

The six fields whose closed value set exists only in the spec's
description prose (no machine-readable `enum`), hand-transcribed from
resource-inventory.md's citations. The schema's CHECK constraints and
the conformance validator both read this, so the two cannot disagree.
`setup_intent.usage` is deliberately absent — an open string with a
documented default, not a closed set (components/discovery.md §5).
"""

DOC_ONLY_ENUMS: dict[str, dict[str, tuple[str, ...]]] = {
    "balance_transaction": {
        "status": ("available", "pending"),
    },
    "dispute": {
        "reason": (
            "bank_cannot_process",
            "check_returned",
            "credit_not_processed",
            "customer_initiated",
            "debit_not_authorized",
            "duplicate",
            "fraudulent",
            "general",
            "incorrect_account_details",
            "insufficient_funds",
            "noncompliant",
            "product_not_received",
            "product_unacceptable",
            "subscription_canceled",
            "unrecognized",
        ),
    },
    "payout": {
        "method": ("standard", "instant"),
        "source_type": ("card", "fpx", "bank_account"),
        "status": ("paid", "pending", "in_transit", "canceled", "failed"),
    },
    "refund": {
        "status": ("pending", "requires_action", "succeeded", "failed", "canceled"),
    },
}
