"""The committed spec pipeline artifacts, generated by `tools_dev/prune_spec.py`.

The data files are generated from the pinned Stripe OpenAPI snapshot — do
not edit them by hand; regenerate with `python -m tools_dev.prune_spec` (the
source spec is git-ignored; see `research/MANIFEST.md`). This `__init__` is
the one hand-written module among them: it re-exports the closed sets the
schema's CHECK constraints, `emit_event` and the conformance validator read
(components/discovery.md), and loads `spec3.min.json` and `schema_rules.json`
once per process for the discovery index, the serializer, the expansion
resolver and the schema-conformance validator. The subset of Stripe's spec in
this directory is MIT-licensed material — see `THIRD_PARTY_LICENSES.md`.
"""

import json
from functools import cache
from importlib import resources
from typing import Any

from seahaven_stripe_world.spec.enums import (
    DECLARED_OVERRIDES,
    DECLINE_CODES,
    DOC_ONLY_ENUMS,
    ENUM_OVERRIDES,
)
from seahaven_stripe_world.spec.event_types import EVENT_TYPES
from seahaven_stripe_world.spec.expandable import EXPANDABLE_FIELDS

__all__ = [
    "DECLARED_OVERRIDES",
    "DECLINE_CODES",
    "DOC_ONLY_ENUMS",
    "ENUM_OVERRIDES",
    "EVENT_TYPES",
    "EXPANDABLE_FIELDS",
    "discovery_index_document",
    "full_spec_document",
    "pinned_version",
    "schema_rules",
    "spec_document",
]


@cache
def pinned_version() -> str:
    """The one API version this world serves, read from the pinned spec itself.

    The conformance recorder re-exports this for every recorded request
    (`tools_dev/scenarios/_dsl.py::PINNED_VERSION`), so the pin on the wire and
    the pin in the served shapes are the same fact rather than two constants.
    """
    return str(spec_document()["info"]["version"])


@cache
def spec_document() -> dict[str, Any]:
    """The pruned spec, parsed once per process.

    ~1.3 MB and ~11 ms to parse (`components/discovery.md` §3), shared by
    reference across every instance a process serves: discovery's index, the
    serializer's presence sets and the expansion resolver all read this one
    copy rather than each opening the file.
    """
    text = resources.files("seahaven_stripe_world.spec").joinpath("spec3.min.json").read_text()
    return json.loads(text)  # type: ignore[no-any-return]


@cache
def full_spec_document() -> dict[str, Any]:
    """The full Stripe OpenAPI spec, parsed once per process.

    ~8 MB — used by the enumeration script and by the discovery index
    (architecture section 5.1). Not loaded at world startup; only
    callers that need the full catalogue import this.
    """
    text = resources.files("seahaven_stripe_world.spec").joinpath("spec3.json").read_text()
    return json.loads(text)  # type: ignore[no-any-return]


@cache
def discovery_index_document() -> dict[str, Any]:
    """The discovery index: one details document per catalogued operation.

    Generated by ``tools_dev/prune_spec.py`` from the full spec and the
    MCP catalogue (architecture §5.1).  Loaded once per process, shared
    across all instances.  ~450 KB, 123 operations.
    """
    text = (
        resources.files("seahaven_stripe_world.spec").joinpath("discovery_index.json").read_text()
    )
    return json.loads(text)  # type: ignore[no-any-return]


@cache
def schema_rules() -> dict[str, Any]:
    """The schema-conformance rule set, parsed once per process.

    The normalized structural rules `validate_object` walks: `by_object` and
    `deleted_by_object` map an `object` discriminator value to its schema,
    `rules` holds each reachable schema's shape (components/conformance.md
    "Schema conformance"). ~140 KB; test-side consumers only, but it travels
    with the package like every other generated artifact so there is exactly
    one copy of the truth.
    """
    text = resources.files("seahaven_stripe_world.spec").joinpath("schema_rules.json").read_text()
    return json.loads(text)  # type: ignore[no-any-return]
